name: test trigger

on:
  issue_comment:
    types: [created]

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/test')
    steps:
      - name: Get PR Data
        uses: actions/github-script@v7
        id: get-pr-data
        with:
          script: |
            console.log(`Get PR info: ${context.repo.owner}/${context.repo.repo}#${context.issue.number}`)
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            core.setOutput('head_sha', pr.head.sha)
            return {
              num: context.issue.number,
              branchName: pr.head.ref,
              commit: pr.head.sha,
              repo: pr.head.repo.full_name
            }

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ fromJSON(steps.get-pr-data.outputs.result).num }}/head
          fetch-depth: 0

      # This step can be removed on May 26 2025
      - name: Check Commit Hash Ambiguity
        id: check_ambiguity
        run: |
          HEAD_SHA=${{ steps.get-pr-data.outputs.head_sha }}
          COMMIT_SHORT=${HEAD_SHA:0:7}

          if git show "$COMMIT_SHORT"; then
            echo "COLLISION=false" >> $GITHUB_ENV
          else
            echo "COLLISION=true" >> $GITHUB_ENV
          fi
